### ISSUE TITLE
Introduce `get_or_init_with` and `get_or_try_init_with`

### ISSUE THREAD

**Issue by MarinPostma** [danieldg/async-once-cell#11]
I have a use case where the `init` future requires some work to be built, but I would like to avoid doing this work unless necessary. I propose the introduction of `get_or_init_with` and `get_or_try_init_with` that take a closure instead of a future:

```rust
    pub async fn get_or_init_with<F, Fut>(&self, init: F) -> &T
    where
        F: FnOnce() -> Fut,
        Fut: Future<Output = T>
```
This way, we can have a lazily constructed future.

I will submit a PR with the proposed changes

**Comment by danieldg** [comment]
You don't need to change `OnceCell` to do this; you can just do it with an `async` block either like this or directly in your calling function (instead of passing in a closure):

```rust
async fn get_or_init_with_closure<T>(cell: &OnceCell<T>, init: impl FnOnce() -> Fut) -> &T
    where Fut: Future<Output=T>
{
    cell.get_or_init(async {
        let inner = init();
        inner.await
    }).await
}
```

The work to build the inner `Future` is only done if the outer `Future` is polled.  This should produce identical behavior to invoking the function added in your patch, as far as when any lines of code are run given the same order of poll operations.

Do you have a use case that this doesn't work for? I'd be interested in some more details if so.
